arm_traj:
  ros__parameters:
    ### ros parameters
    rate_ros: 1000.0
    rate_teleop: 500.0

    ### model parameters
    model_urdf: ""
    model_frame_id: "base_link"
    pose_end_in_flange: [0.187, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

    ### arm trajectory config (from jnt_plan_cfg.json)
    # arm_config
    lim_vel: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    lim_acc: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    jnt_eff: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # task_config
    init_position: [0.0, -1.5, 3.0, 0.0, 0.0, 0.0]
    end_position: [0.0, -1.5, 3.0, 0.0, 0.0, 0.0]
    expected_time: 10.0

    ### waypoints
    waypoints_path: ""
